# Generated by Django 5.1.3 on 2025-01-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anigesser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='original_name',
            field=models.CharField(help_text="Оригинальное название, например 'Sousou no Frieren'.", max_length=300, verbose_name='Название'),
        ),
    ]
