# Generated by Django 5.1.3 on 2025-01-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anigesser', '0002_alter_title_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.FloatField(help_text='Дробь от 0 до 10.', verbose_name='Рейтинг'),
        ),
    ]
