# Generated by Django 5.1.3 on 2025-01-25 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anigesser', '0003_alter_title_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='members',
            field=models.PositiveIntegerField(default=0, help_text='Количество пользователей у тайтла на MAL.', verbose_name='Пользователи'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, verbose_name='URL адрес изображения')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anigesser.title', verbose_name='Тайтл')),
            ],
        ),
    ]
