# Generated by Django 5.1.3 on 2025-01-25 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anigesser', '0005_alter_title_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default='hello', help_text='Короткое описание, до 3 предложений.', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя персонажа')),
                ('url', models.URLField(max_length=1000, verbose_name='URL адрес изображения')),
                ('titles', models.ManyToManyField(to='anigesser.title', verbose_name='Тайтлы')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_url', models.URLField(max_length=1000, verbose_name='URL адрес первого изображения')),
                ('second_url', models.URLField(max_length=1000, verbose_name='URL адрес второго изображения')),
                ('third_url', models.URLField(max_length=1000, verbose_name='URL адрес третьего изображения')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anigesser.title', verbose_name='Тайтл')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
                'order_with_respect_to': 'title',
            },
        ),
        migrations.DeleteModel(
            name='Screenshot',
        ),
    ]
