# Generated by Django 5.1.3 on 2025-01-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anigesser', '0007_studio_title_studio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='studio',
            new_name='studios',
        ),
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='titles', to='anigesser.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='title',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='titles', to='anigesser.theme', verbose_name='Темы'),
        ),
    ]
