# Generated by Django 5.1.3 on 2025-01-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anigesser', '0008_rename_studio_title_studios_alter_title_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.CharField(help_text='Короткое описание, до 500 символов.', max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='original_name',
            field=models.CharField(help_text="Оригинальное название, например 'Sousou no Frieren'.", max_length=300, verbose_name='Оригинальное название'),
        ),
        migrations.CreateModel(
            name='TitleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('title', models.ForeignKey(help_text='Тайтл, к которому относится это название.', on_delete=django.db.models.deletion.CASCADE, related_name='title_names', to='anigesser.title', verbose_name='Тайтл')),
            ],
            options={
                'verbose_name': 'Название',
                'verbose_name_plural': 'Названия',
            },
        ),
    ]
