# Generated by Django 5.1.3 on 2025-01-26 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anigesser', '0009_alter_title_description_alter_title_original_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='titles',
            field=models.ManyToManyField(related_name='characters', to='anigesser.title', verbose_name='Тайтлы'),
        ),
        migrations.AlterField(
            model_name='screenshots',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='anigesser.title', verbose_name='Тайтл'),
        ),
        migrations.AlterField(
            model_name='title',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='anigesser.source', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='anigesser.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='titlename',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Альтернативное название'),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('characters', models.ManyToManyField(blank=True, related_name='days', to='anigesser.character', verbose_name='Персонажи')),
                ('screenshots', models.ManyToManyField(blank=True, related_name='days', to='anigesser.screenshots', verbose_name='Скриншоты')),
                ('titles', models.ManyToManyField(blank=True, related_name='days', to='anigesser.title', verbose_name='Тайтлы')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
                'ordering': ['-date'],
            },
        ),
    ]
