# Generated by Django 5.1.3 on 2025-01-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anigesser', '0010_alter_character_titles_alter_screenshots_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('data', models.TextField(verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы тайтлов'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы тайтлов'},
        ),
        migrations.AddField(
            model_name='title',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL обложки'),
        ),
        migrations.AlterField(
            model_name='character',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL адрес изображения'),
        ),
        migrations.AlterField(
            model_name='screenshots',
            name='first_url',
            field=models.URLField(max_length=500, verbose_name='URL адрес первого изображения'),
        ),
        migrations.AlterField(
            model_name='screenshots',
            name='second_url',
            field=models.URLField(max_length=500, verbose_name='URL адрес второго изображения'),
        ),
        migrations.AlterField(
            model_name='screenshots',
            name='third_url',
            field=models.URLField(max_length=500, verbose_name='URL адрес третьего изображения'),
        ),
    ]
