# Generated by Django 5.1.3 on 2025-01-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anigesser', '0011_suggestion_alter_theme_options_alter_type_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='url',
            field=models.URLField(max_length=300, verbose_name='URL адрес изображения'),
        ),
        migrations.AlterField(
            model_name='screenshots',
            name='first_url',
            field=models.URLField(max_length=300, verbose_name='URL адрес первого изображения'),
        ),
        migrations.AlterField(
            model_name='screenshots',
            name='second_url',
            field=models.URLField(max_length=300, verbose_name='URL адрес второго изображения'),
        ),
        migrations.AlterField(
            model_name='screenshots',
            name='third_url',
            field=models.URLField(max_length=300, verbose_name='URL адрес третьего изображения'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='data',
            field=models.CharField(max_length=500, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='url',
            field=models.URLField(max_length=300, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='title',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, verbose_name='URL обложки'),
        ),
    ]
