# Generated by Django 5.1.3 on 2025-01-31 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anigesser', '0012_alter_character_url_alter_screenshots_first_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='data',
            field=models.CharField(blank=True, max_length=500, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
